package com.example.vivacventuresmobile.common

object Constantes {
    const val AUTHORIZATION = "Authorization"
    const val BEARER = "Bearer "
    const val USERORPASS_INCORRECT = "Usuario o contraseña incorrectos"
    const val USER_EXISTS = "El usuario o el email ya existe"
    const val ERROR_DESCONOCIDO = "Error desconocido"
    const val REFRESH_TOKEN = "RefreshToken"
    const val APP_DB = "app.db"
    const val ORDERS = "orders"
    const val DATA_STORE = "data_store"
    const val REFRESHTOKEN = "refresh_token"
    const val ACCESS_TOKEN = "access_token"
    const val DISMISS = "Dismiss"
    const val NO_PERMISSION = "You need admin permission"
    const val REGISTER_PATH = "/auth/register"
    const val LOGIN_PATH = "/auth/login"
    const val REFRESH_PATH = "/auth/refresh"
    const val FORGOTPASSWORDPATH = "/auth/forgotPassword"
    const val RESETPATH = "/auth/resetPassword"
    const val TOKEN = "token"
    const val FORBIDDEN = "Forbidden"
    const val VERIFY_EMAIL = "Verify your email"

    const val EMAIL = "email"
    const val PASSWORD = "password"
    const val NEWPASSWORD = "newPassword"
    const val TEMPORALPASSWORD = "temporalPassword"
    const val USER = "user"
    const val USERNAME = "username"
    const val REGISTER = "register"
    const val LOGIN = "login"
}
